name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git LFS
        run: |
          git lfs install
          git lfs track "images/demo.gif"
          git lfs track "images/demo.png"
      - name: Ignore binary files
        run: |
          echo "images/demo.gif" >> .gitignore
          echo "images/demo.png" >> .gitignore
          git add .gitignore
          git commit -m "Ignore binary files"
      - name: Add remote 
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git remote add space https://AaronBarbosa:$HF@huggingface.co/spaces/AaronBarbosa/twitter_sentiment
      - name: Push to hub
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git push --force https://AaronBarbosa:$HF@huggingface.co/spaces/AaronBarbosa/twitter_sentiment main
